import { contextBridge, ipcRenderer } from 'electron';
import type { AriseApi } from '@arise/shared';
import {
  appInfoSchema,
  chartCatalogSchema,
  chartMarketObjectSchema,
  createChartObjectInputSchema,
  createFolderInputSchema,
  createIdeaInputSchema,
  createIdeaResultSchema,
  createKnowledgeDocumentInputSchema,
  createPlanningIdeaInputSchema,
  createReviewScheduleInputSchema,
  folderSchema,
  getKnowledgeDocumentInputSchema,
  ipcChannels,
  knowledgeDocumentDetailSchema,
  knowledgeLibrarySchema,
  listChartObjectsInputSchema,
  listChartObjectsResultSchema,
  listIdeasResultSchema,
  listPlanningIdeasResultSchema,
  moveKnowledgeDocumentInputSchema,
  planningIdeaSchema,
  queueReviewNowInputSchema,
  resolveMarketReviewInputSchema,
  reviewQueueEntrySchema,
  reviewScheduleViewSchema,
  reviewWorkspaceSchema,
  reviseChartObjectInputSchema,
  saveKnowledgeDocumentInputSchema,
  transitionPlanningIdeaInputSchema,
  updatePlanningThesisInputSchema,
  createStrategyDefinitionInputSchema,
  reviseStrategyDefinitionInputSchema,
  createStrategyMapInputSchema,
  saveStrategyMapInputSchema,
  selectStrategyPackageResultSchema,
  importStrategyPackageInputSchema,
  importStrategyPackageResultSchema,
  exportStrategyPackageInputSchema,
  exportStrategyPackageResultSchema,
  strategyDefinitionViewSchema,
  strategyMapViewSchema,
  strategyWorkspaceSchema,
  createStrategyRuntimeInputSchema,
  simulateStrategyRuntimeEventInputSchema,
  manualStrategyRuntimeDecisionInputSchema,
  strategyRuntimeViewSchema,
  evidenceWorkspaceSchema,
  regenerateEvidenceSnapshotInputSchema,
  regenerateEvidenceSnapshotResultSchema,
  classifyExternalPositionInputSchema,
  mt5WorkspaceSchema,
  executionWorkspaceSchema,
  executeActionProposalInputSchema,
  protectionWorkspaceSchema,
  createProtectionRuleInputSchema,
  recordProtectionTriggerInputSchema,
  executeProtectionProposalInputSchema,
  configureColonyAutomationInputSchema,
  invalidateColonyThesisInputSchema,
  setColonyCooldownInputSchema,
  resetAttemptPeriodInputSchema,
  analyticsWorkspaceSchema,
  performanceReviewWorkspaceSchema,
  createPerformanceReviewInputSchema,
  revisePerformanceReviewInputSchema,
  createLessonInputSchema,
  advanceLessonInputSchema,
  createStrategyChangeProposalInputSchema,
  acceptStrategyChangeProposalInputSchema,
} from '@arise/shared';

const api: AriseApi = {
  getAppInfo: async () => appInfoSchema.parse(await ipcRenderer.invoke(ipcChannels.getAppInfo)),
  createIdea: async (input) => createIdeaResultSchema.parse(await ipcRenderer.invoke(ipcChannels.createIdea, createIdeaInputSchema.parse(input))),
  listIdeas: async () => listIdeasResultSchema.parse(await ipcRenderer.invoke(ipcChannels.listIdeas)),
  getChartCatalog: async () => chartCatalogSchema.parse(await ipcRenderer.invoke(ipcChannels.getChartCatalog)),
  listChartObjects: async (input) => listChartObjectsResultSchema.parse(await ipcRenderer.invoke(ipcChannels.listChartObjects, listChartObjectsInputSchema.parse(input))),
  createChartObject: async (input) => chartMarketObjectSchema.parse(await ipcRenderer.invoke(ipcChannels.createChartObject, createChartObjectInputSchema.parse(input))),
  reviseChartObject: async (input) => chartMarketObjectSchema.parse(await ipcRenderer.invoke(ipcChannels.reviseChartObject, reviseChartObjectInputSchema.parse(input))),
  listPlanningIdeas: async () => listPlanningIdeasResultSchema.parse(await ipcRenderer.invoke(ipcChannels.listPlanningIdeas)),
  createPlanningIdea: async (input) => planningIdeaSchema.parse(await ipcRenderer.invoke(ipcChannels.createPlanningIdea, createPlanningIdeaInputSchema.parse(input))),
  updatePlanningThesis: async (input) => planningIdeaSchema.parse(await ipcRenderer.invoke(ipcChannels.updatePlanningThesis, updatePlanningThesisInputSchema.parse(input))),
  transitionPlanningIdea: async (input) => planningIdeaSchema.parse(await ipcRenderer.invoke(ipcChannels.transitionPlanningIdea, transitionPlanningIdeaInputSchema.parse(input))),
  getKnowledgeLibrary: async () => knowledgeLibrarySchema.parse(await ipcRenderer.invoke(ipcChannels.getKnowledgeLibrary)),
  getKnowledgeDocument: async (input) => knowledgeDocumentDetailSchema.parse(await ipcRenderer.invoke(ipcChannels.getKnowledgeDocument, getKnowledgeDocumentInputSchema.parse(input))),
  createKnowledgeDocument: async (input) => knowledgeDocumentDetailSchema.parse(await ipcRenderer.invoke(ipcChannels.createKnowledgeDocument, createKnowledgeDocumentInputSchema.parse(input))),
  saveKnowledgeDocument: async (input) => knowledgeDocumentDetailSchema.parse(await ipcRenderer.invoke(ipcChannels.saveKnowledgeDocument, saveKnowledgeDocumentInputSchema.parse(input))),
  createKnowledgeFolder: async (input) => folderSchema.parse(await ipcRenderer.invoke(ipcChannels.createKnowledgeFolder, createFolderInputSchema.parse(input))),
  moveKnowledgeDocument: async (input) => knowledgeDocumentDetailSchema.parse(await ipcRenderer.invoke(ipcChannels.moveKnowledgeDocument, moveKnowledgeDocumentInputSchema.parse(input))),
  getReviewWorkspace: async () => reviewWorkspaceSchema.parse(await ipcRenderer.invoke(ipcChannels.getReviewWorkspace)),
  createReviewSchedule: async (input) => reviewScheduleViewSchema.parse(await ipcRenderer.invoke(ipcChannels.createReviewSchedule, createReviewScheduleInputSchema.parse(input))),
  queueReviewNow: async (input) => reviewQueueEntrySchema.parse(await ipcRenderer.invoke(ipcChannels.queueReviewNow, queueReviewNowInputSchema.parse(input))),
  resolveMarketReview: async (input) => reviewQueueEntrySchema.parse(await ipcRenderer.invoke(ipcChannels.resolveMarketReview, resolveMarketReviewInputSchema.parse(input))),
  getStrategyWorkspace: async () => strategyWorkspaceSchema.parse(await ipcRenderer.invoke(ipcChannels.getStrategyWorkspace)),
  createStrategyDefinition: async (input) => strategyDefinitionViewSchema.parse(await ipcRenderer.invoke(ipcChannels.createStrategyDefinition, createStrategyDefinitionInputSchema.parse(input))),
  reviseStrategyDefinition: async (input) => strategyDefinitionViewSchema.parse(await ipcRenderer.invoke(ipcChannels.reviseStrategyDefinition, reviseStrategyDefinitionInputSchema.parse(input))),
  createStrategyMap: async (input) => strategyMapViewSchema.parse(await ipcRenderer.invoke(ipcChannels.createStrategyMap, createStrategyMapInputSchema.parse(input))),
  saveStrategyMap: async (input) => strategyMapViewSchema.parse(await ipcRenderer.invoke(ipcChannels.saveStrategyMap, saveStrategyMapInputSchema.parse(input))),
  selectStrategyPackage: async () => selectStrategyPackageResultSchema.parse(await ipcRenderer.invoke(ipcChannels.selectStrategyPackage)),
  importStrategyPackage: async (input) => importStrategyPackageResultSchema.parse(await ipcRenderer.invoke(ipcChannels.importStrategyPackage, importStrategyPackageInputSchema.parse(input))),
  exportStrategyPackage: async (input) => exportStrategyPackageResultSchema.parse(await ipcRenderer.invoke(ipcChannels.exportStrategyPackage, exportStrategyPackageInputSchema.parse(input))),
  createStrategyRuntime: async (input) => strategyRuntimeViewSchema.parse(await ipcRenderer.invoke(ipcChannels.createStrategyRuntime, createStrategyRuntimeInputSchema.parse(input))),
  simulateStrategyRuntimeEvent: async (input) => strategyRuntimeViewSchema.parse(await ipcRenderer.invoke(ipcChannels.simulateStrategyRuntimeEvent, simulateStrategyRuntimeEventInputSchema.parse(input))),
  manualStrategyRuntimeDecision: async (input) => strategyRuntimeViewSchema.parse(await ipcRenderer.invoke(ipcChannels.manualStrategyRuntimeDecision, manualStrategyRuntimeDecisionInputSchema.parse(input))),
  getEvidenceWorkspace: async () => evidenceWorkspaceSchema.parse(await ipcRenderer.invoke(ipcChannels.getEvidenceWorkspace)),
  regenerateEvidenceSnapshot: async (input) => regenerateEvidenceSnapshotResultSchema.parse(await ipcRenderer.invoke(ipcChannels.regenerateEvidenceSnapshot, regenerateEvidenceSnapshotInputSchema.parse(input))),
  getMt5Workspace: async () => mt5WorkspaceSchema.parse(await ipcRenderer.invoke(ipcChannels.getMt5Workspace)),
  classifyExternalPosition: async (input) => mt5WorkspaceSchema.parse(await ipcRenderer.invoke(ipcChannels.classifyExternalPosition, classifyExternalPositionInputSchema.parse(input))),
  reconcileMt5: async () => mt5WorkspaceSchema.parse(await ipcRenderer.invoke(ipcChannels.reconcileMt5)),
  getExecutionWorkspace:async()=>executionWorkspaceSchema.parse(await ipcRenderer.invoke(ipcChannels.getExecutionWorkspace)),
  executeActionProposal:async(input)=>executionWorkspaceSchema.parse(await ipcRenderer.invoke(ipcChannels.executeActionProposal,executeActionProposalInputSchema.parse(input))),
  getProtectionWorkspace:async()=>protectionWorkspaceSchema.parse(await ipcRenderer.invoke(ipcChannels.getProtectionWorkspace)),
  createProtectionRule:async(input)=>protectionWorkspaceSchema.parse(await ipcRenderer.invoke(ipcChannels.createProtectionRule,createProtectionRuleInputSchema.parse(input))),
  recordProtectionTrigger:async(input)=>protectionWorkspaceSchema.parse(await ipcRenderer.invoke(ipcChannels.recordProtectionTrigger,recordProtectionTriggerInputSchema.parse(input))),
  executeProtectionProposal:async(input)=>protectionWorkspaceSchema.parse(await ipcRenderer.invoke(ipcChannels.executeProtectionProposal,executeProtectionProposalInputSchema.parse(input))),
  configureColonyAutomation:async(input)=>protectionWorkspaceSchema.parse(await ipcRenderer.invoke(ipcChannels.configureColonyAutomation,configureColonyAutomationInputSchema.parse(input))),
  invalidateColonyThesis:async(input)=>protectionWorkspaceSchema.parse(await ipcRenderer.invoke(ipcChannels.invalidateColonyThesis,invalidateColonyThesisInputSchema.parse(input))),
  setColonyCooldown:async(input)=>protectionWorkspaceSchema.parse(await ipcRenderer.invoke(ipcChannels.setColonyCooldown,setColonyCooldownInputSchema.parse(input))),
  resetAttemptPeriod:async(input)=>protectionWorkspaceSchema.parse(await ipcRenderer.invoke(ipcChannels.resetAttemptPeriod,resetAttemptPeriodInputSchema.parse(input))),
  getAnalyticsWorkspace:async()=>analyticsWorkspaceSchema.parse(await ipcRenderer.invoke(ipcChannels.getAnalyticsWorkspace)),
  getPerformanceReviewWorkspace:async()=>performanceReviewWorkspaceSchema.parse(await ipcRenderer.invoke(ipcChannels.getPerformanceReviewWorkspace)),
  createPerformanceReview:async(input)=>performanceReviewWorkspaceSchema.parse(await ipcRenderer.invoke(ipcChannels.createPerformanceReview,createPerformanceReviewInputSchema.parse(input))),
  revisePerformanceReview:async(input)=>performanceReviewWorkspaceSchema.parse(await ipcRenderer.invoke(ipcChannels.revisePerformanceReview,revisePerformanceReviewInputSchema.parse(input))),
  createLesson:async(input)=>performanceReviewWorkspaceSchema.parse(await ipcRenderer.invoke(ipcChannels.createLesson,createLessonInputSchema.parse(input))),
  advanceLesson:async(input)=>performanceReviewWorkspaceSchema.parse(await ipcRenderer.invoke(ipcChannels.advanceLesson,advanceLessonInputSchema.parse(input))),
  createStrategyChangeProposal:async(input)=>performanceReviewWorkspaceSchema.parse(await ipcRenderer.invoke(ipcChannels.createStrategyChangeProposal,createStrategyChangeProposalInputSchema.parse(input))),
  acceptStrategyChangeProposal:async(input)=>performanceReviewWorkspaceSchema.parse(await ipcRenderer.invoke(ipcChannels.acceptStrategyChangeProposal,acceptStrategyChangeProposalInputSchema.parse(input))),
};

contextBridge.exposeInMainWorld('arise', api);
