import {_electron as electron,expect,test} from '@playwright/test';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
import {FakeExecutionBroker,ReadOnlyMt5AgentServer} from '@arise/mt5-agent';
import {mt5SnapshotSchema} from '@arise/shared';

test('M10 SHADOW freezes an auditable plan without emitting a broker command and survives restart',async()=>{
  test.setTimeout(90_000);const userData=await mkdtemp(path.join(tmpdir(),'arise-m10-shadow-'));const launch=()=>electron.launch({args:['.',`--user-data-dir=${userData}`]});let app:Awaited<ReturnType<typeof launch>>|undefined;
  try{app=await launch();let page=await app.firstWindow();const seeded=await page.evaluate(async()=>{const colony=await window.arise.createPlanningIdea({symbol:'EURUSD',timeframe:'D',direction:'LONG',thesisText:'M10 shadow thesis',targetDescription:'Target',invalidationDescription:'Invalidation',primaryTargetMarketObjectVersionId:null,invalidationMarketObjectVersionId:null});const strategy=await window.arise.createStrategyDefinition({name:'M10 Demo Gate',category:'ENTRY',description:'M10 deterministic entry gate',tags:['m10'],automationCapability:'AUTOMATABLE',deploymentStatus:'VALIDATED',detectorKey:'price_touch',detectorVersion:'1',evaluationMode:'ON_PRICE_UPDATE',parameterSchema:{}});const map=await window.arise.createStrategyMap({name:'M10 Shadow Scout',kind:'STRATEGY_MAP',graph:{nodes:[{id:'gate',family:'STRATEGY',label:'Gate',position:{x:80,y:80},timeframe:'M5',purposes:['ENTRY'],importance:'REQUIRED',executionMode:'AUTO',strategyVersionId:strategy.versionId,parameters:{level:1.1,tolerancePips:0}},{id:'scout',family:'ACTION',label:'Create Scout',position:{x:330,y:80},timeframe:'M5',purposes:['ENTRY'],importance:'REQUIRED',executionMode:'AUTO',actionKey:'create_scout',parameters:{canonicalSymbol:'EURUSD',direction:'LONG',gearId:'GEAR_1',lots:0.1,initialStop:1.09,referencePrice:1.1,expiresInSeconds:30,maxSpreadPips:2,stackingEligible:true,riskFresh:true,sessionPermitted:true,newsPermitted:true}}],edges:[{id:'gate-scout',sourceNodeId:'gate',targetNodeId:'scout',sourcePort:'out',targetPort:'in'}]}});const runtime=await window.arise.createStrategyRuntime({mapId:map.mapId,colonyId:colony.colonyId,mode:'SHADOW'});await window.arise.simulateStrategyRuntimeEvent({runtimeId:runtime.runtimeId,eventType:'PRICE_UPDATE',timeframe:'M5',price:1.1,spreadPips:1,pipSize:0.0001,candle:null,states:{}});const finished=await window.arise.simulateStrategyRuntimeEvent({runtimeId:runtime.runtimeId,eventType:'EVENT',timeframe:'M5',price:1.1,spreadPips:1,pipSize:0.0001,candle:null,states:{}});const proposal=finished.actionProposals[0];if(!proposal)throw new Error('Expected CREATE_SCOUT proposal');const execution=await window.arise.executeActionProposal({proposalCorrelationId:proposal.correlationId});return {execution,correlationId:proposal.correlationId};});expect(seeded.execution.plans).toHaveLength(1);expect(seeded.execution.lifecycles[0]).toMatchObject({state:'SHADOW_COMPLETED',filledVolume:0,protectedVolume:0});expect(seeded.execution.commands).toHaveLength(0);await app.close();app=undefined;app=await launch();page=await app.firstWindow();const restored=await page.evaluate(()=>window.arise.getExecutionWorkspace());expect(restored.intents).toHaveLength(1);expect(restored.plans).toHaveLength(1);expect(restored.commands).toHaveLength(0);expect(restored.lifecycles[0]?.state).toBe('SHADOW_COMPLETED');}
  finally{await app?.close();await rm(userData,{recursive:true,force:true});}
});

test('M10 DEMO uses the gateway and materializes only after broker fill and verified initial protection',async()=>{
  test.setTimeout(90_000);const stamp=()=>new Date().toISOString();const broker=new FakeExecutionBroker();const agent=new ReadOnlyMt5AgentServer({mode:'FAKE_HARNESS',fakeBroker:broker,terminalConnected:()=>true,snapshot:()=>mt5SnapshotSchema.parse({snapshotId:randomUUID(),complete:true,capturedAt:stamp(),account:{accountKey:'fake:demo-m10',broker:'Fake MT5',server:'Harness',login:'1010',currency:'USD',balance:10000,equity:10000,margin:0,freeMargin:10000,leverage:100,isLive:false,hedging:true,capturedAt:stamp()},symbols:[{brokerSymbol:'EURUSD.a',canonicalSymbol:'EURUSD',digits:5,tickSize:.00001,pipSize:.0001,contractSize:100000,minVolume:.01,volumeStep:.01,maxVolume:100,stopsLevel:0,freezeLevel:0}],positions:[],pendingOrders:[],quotes:[{brokerSymbol:'EURUSD.a',bid:1.1,ask:1.1001,brokerTime:stamp(),receivedAt:stamp(),sequence:1}],candles:[],unavailableReason:null})});const address=await agent.start();const userData=await mkdtemp(path.join(tmpdir(),'arise-m10-demo-'));const app=await electron.launch({args:['.',`--user-data-dir=${userData}`],env:{...process.env,ARISE_MT5_ENDPOINT:`${address.host}:${address.port}`}});
  try{const page=await app.firstWindow();await expect.poll(async()=>page.evaluate(async()=>(await window.arise.getMt5Workspace()).connection.state)).toBe('CONNECTED');const commandId=await page.evaluate(async()=>{const colony=await window.arise.createPlanningIdea({symbol:'EURUSD',timeframe:'D',direction:'LONG',thesisText:'M10 demo thesis',targetDescription:'Target',invalidationDescription:'Invalidation',primaryTargetMarketObjectVersionId:null,invalidationMarketObjectVersionId:null});const strategy=await window.arise.createStrategyDefinition({name:'M10 Demo Entry',category:'ENTRY',description:'M10 demo',tags:['m10'],automationCapability:'AUTOMATABLE',deploymentStatus:'DEMO_APPROVED',detectorKey:'price_touch',detectorVersion:'1',evaluationMode:'ON_PRICE_UPDATE',parameterSchema:{}});const map=await window.arise.createStrategyMap({name:'M10 Demo Map',kind:'STRATEGY_MAP',graph:{nodes:[{id:'gate',family:'STRATEGY',label:'Gate',position:{x:80,y:80},timeframe:'M5',purposes:['ENTRY'],importance:'REQUIRED',executionMode:'AUTO',strategyVersionId:strategy.versionId,parameters:{level:1.1,tolerancePips:0}},{id:'scout',family:'ACTION',label:'Create Scout',position:{x:330,y:80},timeframe:'M5',purposes:['ENTRY'],importance:'REQUIRED',executionMode:'AUTO',actionKey:'create_scout',parameters:{canonicalSymbol:'EURUSD',direction:'LONG',gearId:'GEAR_1',lots:0.1,initialStop:1.09,expiresInSeconds:30,maxSpreadPips:2,stackingEligible:true,riskFresh:true,sessionPermitted:true,newsPermitted:true}}],edges:[{id:'gate-scout',sourceNodeId:'gate',targetNodeId:'scout',sourcePort:'out',targetPort:'in'}]}});const runtime=await window.arise.createStrategyRuntime({mapId:map.mapId,colonyId:colony.colonyId,mode:'DEMO'});await window.arise.simulateStrategyRuntimeEvent({runtimeId:runtime.runtimeId,eventType:'PRICE_UPDATE',timeframe:'M5',price:1.1,spreadPips:1,pipSize:.0001,candle:null,states:{}});const done=await window.arise.simulateStrategyRuntimeEvent({runtimeId:runtime.runtimeId,eventType:'EVENT',timeframe:'M5',price:1.1,spreadPips:1,pipSize:.0001,candle:null,states:{}});const proposal=done.actionProposals[0];if(!proposal)throw new Error('Expected proposal');const execution=await window.arise.executeActionProposal({proposalCorrelationId:proposal.correlationId});return execution.commands[0]?.commandId??'';});expect(commandId).not.toBe('');await expect.poll(async()=>page.evaluate(async()=>(await window.arise.getExecutionWorkspace()).lifecycles[0]?.state)).toBe('ACTIVE');const execution=await page.evaluate(()=>window.arise.getExecutionWorkspace());expect(execution.commands[0]).toMatchObject({commandId,status:'COMPLETED',attemptCount:1});expect(execution.lifecycles[0]).toMatchObject({filledVolume:.1,protectedVolume:.1});expect(broker.exposureCount).toBe(1);}
  finally{await app.close();await agent.stop();await rm(userData,{recursive:true,force:true});}
});
