import { useEffect, useMemo, useState } from 'react';
import type { AriseApi } from '@arise/shared';

type Workspace=Awaited<ReturnType<AriseApi['getAnalyticsWorkspace']>>;
type Metric=Workspace['overall']['realizedPips'];
type PnlMode='PIP-FIRST'|'PIPS + MONEY'|'MONEY-FIRST'|'$ HIDDEN';
type Unit='PIPS'|'POSITION-PIPS'|'MONEY';
const EMPTY:Workspace={asOf:new Date(0).toISOString(),overall:{colonyId:'ALL',positionCount:0,scoutCount:0,attemptCount:0,realizedPips:{status:'AVAILABLE',value:0,reason:null},openPips:{status:'AVAILABLE',value:0,reason:null},positionPips:{status:'AVAILABLE',value:0,reason:null},scoutingCost:{status:'AVAILABLE',value:0,reason:null},protectedPips:{status:'AVAILABLE',value:0,reason:null},averageScoutLoss:{status:'UNAVAILABLE',value:null,reason:'No Scouts.'},survivorContribution:{status:'AVAILABLE',value:0,reason:null},longestLivedLegMs:{status:'UNAVAILABLE',value:null,reason:'No Legs.'},millipedeEfficiency:{status:'UNAVAILABLE',value:null,reason:'No denominator.'},wins:0,losses:0,breakevens:0,incompleteOutcomes:0},money:{realized:{status:'AVAILABLE',value:0,reason:null},open:{status:'AVAILABLE',value:0,reason:null},total:{status:'AVAILABLE',value:0,reason:null}},positions:[],colonies:[],groups:{TIMEFRAME:{groups:[],unavailableCount:0},STRATEGY:{groups:[],unavailableCount:0},COMBO:{groups:[],unavailableCount:0},TEMPLATE:{groups:[],unavailableCount:0},ENTRY_HOUR:{groups:[],unavailableCount:0},WEEKDAY:{groups:[],unavailableCount:0},SESSION:{groups:[],unavailableCount:0},TAG:{groups:[],unavailableCount:0},DIRECTION:{groups:[],unavailableCount:0},QUALIFICATION:{groups:[],unavailableCount:0}},curve:[],curves:{balance:[],equity:[]}};

function MetricValue({metric,suffix=''}:{readonly metric:Metric;readonly suffix?:string}){
  if(metric.status==='UNAVAILABLE')return <span className="metric-unavailable" title={metric.reason}>UNAVAILABLE</span>;
  return <>{Number.isInteger(metric.value)?metric.value:metric.value.toFixed(2)}{suffix}</>;
}
function DurationValue({metric}:{readonly metric:Metric}){if(metric.status==='UNAVAILABLE')return <span className="metric-unavailable" title={metric.reason}>UNAVAILABLE</span>;const hours=metric.value/3_600_000;return <>{hours<24?`${hours.toFixed(1)}h`:`${(hours/24).toFixed(1)}d`}</>;}
type SeriesPoint={readonly occurredAt:string;readonly pips:number|null;readonly positionPips:number|null;readonly money:number|null};
function Curve({series,unit}:{readonly series:readonly {readonly name:string;readonly data:readonly SeriesPoint[]}[];readonly unit:Unit}){
  const lines=useMemo(()=>series.map((item)=>({name:item.name,points:item.data.map((point)=>({x:Date.parse(point.occurredAt),y:unit==='PIPS'?point.pips:unit==='POSITION-PIPS'?point.positionPips:point.money}))})),[series,unit]);
  const points=lines.flatMap((line)=>line.points).filter((point):point is {x:number;y:number}=>point.y!==null);if(!points.length)return <div className="analytics-empty">No complete {unit.toLowerCase()} series is available yet.</div>;
  const minX=Math.min(...points.map((point)=>point.x)),maxX=Math.max(...points.map((point)=>point.x));const minY=Math.min(0,...points.map((point)=>point.y)),maxY=Math.max(0,...points.map((point)=>point.y));
  const path=(values:readonly {x:number;y:number|null}[])=>{let segmentOpen=false;return values.map((point)=>{if(point.y===null){segmentOpen=false;return '';}const command=segmentOpen?'L':'M';segmentOpen=true;return `${command} ${20+(maxX===minX?0:(point.x-minX)/(maxX-minX))*560} ${165-(maxY===minY?.5:(point.y-minY)/(maxY-minY))*135}`;}).join(' ');};
  return <svg aria-label={`${unit} performance curve`} viewBox="0 0 600 180" preserveAspectRatio="none">{lines.map((line)=><path key={line.name} className={line.name.toLowerCase()} d={path(line.points)}/>)}</svg>;
}

export function AnalyticsWorkspace({pnlMode}:{readonly pnlMode:PnlMode}){
  const [data,setData]=useState<Workspace>(EMPTY);const [unit,setUnit]=useState<Unit>(pnlMode==='MONEY-FIRST'?'MONEY':'PIPS');const [view,setView]=useState<'BALANCE'|'EQUITY'|'BOTH'>('BOTH');const [dimension,setDimension]=useState<keyof Workspace['groups']>('TIMEFRAME');const [error,setError]=useState<string|null>(null);
  useEffect(()=>{if(window.arise)void window.arise.getAnalyticsWorkspace().then(setData).catch((value:unknown)=>setError(value instanceof Error?value.message:String(value)));},[]);
  useEffect(()=>{if(pnlMode==='$ HIDDEN'&&unit==='MONEY')setUnit('PIPS');},[pnlMode,unit]);
  const group=data.groups[dimension];const completed=data.overall.wins+data.overall.losses+data.overall.breakevens;const winRate=completed?data.overall.wins/completed*100:null;
  return <div className="page-stack page-fill analytics-workspace"><div className="page-header"><div><div className="eyebrow">STUDY</div><h1>Analytics</h1><p>Pip-first Colony and Position research reconstructed from immutable fills, versions, lifecycle and evidence facts.</p></div><div className="analytics-unit-switch"><button className={unit==='PIPS'?'selected':''} onClick={()=>setUnit('PIPS')}>PIPS</button><button className={unit==='POSITION-PIPS'?'selected':''} onClick={()=>setUnit('POSITION-PIPS')}>POSITION-PIPS</button><button disabled={pnlMode==='$ HIDDEN'} className={unit==='MONEY'?'selected':''} onClick={()=>setUnit('MONEY')}>MONEY</button></div></div>
    {pnlMode==='$ HIDDEN'?<div className="review-notice" data-testid="money-hidden-notice"><div><strong>$ HIDDEN is active globally.</strong><span>Raw monetary facts remain preserved, but Analytics will not render their values.</span></div></div>:null}
    <div className="analytics-metrics">
      <article><span>REALIZED PIPS</span><strong><MetricValue metric={data.overall.realizedPips} suffix="p"/></strong></article><article><span>OPEN PIPS</span><strong><MetricValue metric={data.overall.openPips} suffix="p"/></strong></article><article><span>POSITION-PIPS</span><strong><MetricValue metric={data.overall.positionPips}/></strong></article><article><span>SCOUTING COST</span><strong><MetricValue metric={data.overall.scoutingCost} suffix="p"/></strong></article><article><span>PROTECTED PIPS</span><strong><MetricValue metric={data.overall.protectedPips}/></strong></article><article><span>MILLIPEDE EFFICIENCY</span><strong><MetricValue metric={data.overall.millipedeEfficiency}/></strong></article><article><span>AVG SCOUT LOSS</span><strong><MetricValue metric={data.overall.averageScoutLoss} suffix="p"/></strong></article><article><span>SURVIVOR CONTRIBUTION</span><strong><MetricValue metric={data.overall.survivorContribution}/></strong></article><article><span>LONGEST-LIVED LEG</span><strong><DurationValue metric={data.overall.longestLivedLegMs}/></strong></article>{pnlMode!=='$ HIDDEN'?<><article><span>REALIZED MONEY</span><strong><MetricValue metric={data.money.realized}/></strong></article><article><span>OPEN MONEY</span><strong><MetricValue metric={data.money.open}/></strong></article><article><span>TOTAL MONEY</span><strong><MetricValue metric={data.money.total}/></strong></article></>:null}
    </div>
    <div className="analytics-main"><section className="panel chart-panel"><header><div><span className="section-label">PERFORMANCE</span><strong>{unit}</strong></div><div className="analytics-view-switch">{(['EQUITY','BALANCE','BOTH'] as const).map((value)=><button key={value} className={view===value?'selected':''} onClick={()=>setView(value)}>{value}</button>)}</div><small>Immutable exits and timestamped marks · unavailable is never plotted as zero</small></header><Curve series={view==='BALANCE'?[{name:'BALANCE',data:data.curves.balance}]:view==='EQUITY'?[{name:'EQUITY',data:data.curves.equity}]:[{name:'BALANCE',data:data.curves.balance},{name:'EQUITY',data:data.curves.equity}]} unit={unit}/></section><section className="panel analytics-outcomes"><span className="section-label">OUTCOMES · SECONDARY</span><div><b>{data.overall.wins}</b><small>WIN</small></div><div><b>{data.overall.losses}</b><small>LOSS</small></div><div><b>{data.overall.breakevens}</b><small>BE</small></div><div><b>{data.overall.incompleteOutcomes}</b><small>INCOMPLETE</small></div><p>Win rate: {winRate===null?'UNAVAILABLE':`${winRate.toFixed(1)}%`}</p></section></div>
    <section className="panel analytics-breakdown"><header><div><span className="section-label">PERFORMANCE BY</span><select value={dimension} onChange={(event)=>setDimension(event.target.value as keyof Workspace['groups'])}>{Object.keys(data.groups).map((key)=><option key={key}>{key}</option>)}</select></div><small>{group.unavailableCount} Position{group.unavailableCount===1?'':'s'} unavailable for this dimension</small></header>{group.groups.length?<div className="analytics-table"><div className="analytics-table-head"><span>GROUP</span><span>POSITIONS</span><span>REALIZED</span><span>POSITION-PIPS</span><span>W / L / BE</span></div>{group.groups.map((row)=><div key={row.key}><strong>{row.key}</strong><span>{row.positions}</span><span><MetricValue metric={row.realizedPips}/></span><span><MetricValue metric={row.positionPips}/></span><span>{row.wins} / {row.losses} / {row.breakevens}</span></div>)}</div>:<div className="analytics-empty">No supported {dimension.toLowerCase().replaceAll('_',' ')} facts are available.</div>}</section>
    <section className="panel analytics-colonies"><header><div><span className="section-label">COLONIES</span><strong>Lineage-aware campaign attribution</strong></div><small>{data.colonies.length} Colonies</small></header>{data.colonies.length?<div className="analytics-table"><div className="analytics-table-head"><span>COLONY</span><span>SCOUTS</span><span>SCOUT COST</span><span>SURVIVOR</span><span>EFFICIENCY</span></div>{data.colonies.map((colony)=><div key={colony.colonyId}><strong>{colony.symbol} · {colony.label}<small>{colony.lineageColonyIds.length>1?` · ${colony.lineageColonyIds.length} linked Colonies`:''}</small></strong><span>{colony.lineageAnalytics.scoutCount}</span><span><MetricValue metric={colony.lineageAnalytics.scoutingCost}/></span><span><MetricValue metric={colony.lineageAnalytics.survivorContribution}/></span><span><MetricValue metric={colony.lineageAnalytics.millipedeEfficiency}/></span></div>)}</div>:<div className="analytics-empty">No Colonies exist yet. Counts are zero; ratios remain unavailable.</div>}</section>
    <section className="panel analytics-colonies"><header><div><span className="section-label">POSITIONS · SCOUTS · LEGS · RUNNERS</span><strong>Individual identity preserved</strong></div><small>{data.positions.length} Positions</small></header>{data.positions.length?<div className="analytics-table"><div className="analytics-table-head"><span>POSITION</span><span>STATE</span><span>REALIZED</span><span>OPEN</span><span>POSITION-PIPS</span></div>{data.positions.map((position)=><div key={position.positionId}><strong>{position.positionId}</strong><span>{position.currentState}</span><span><MetricValue metric={position.realizedPips}/></span><span><MetricValue metric={position.openPips}/></span><span><MetricValue metric={position.positionPips}/></span></div>)}</div>:<div className="analytics-empty">No broker-confirmed Position facts exist yet.</div>}</section>
    {error?<div className="error">{error}</div>:null}
  </div>;
}
