import { useEffect, useMemo, useState } from 'react';
import type { AriseApi } from '@arise/shared';
import { Icon } from './icons';

type Workspace=Awaited<ReturnType<AriseApi['getPerformanceReviewWorkspace']>>;
type Analytics=Awaited<ReturnType<AriseApi['getAnalyticsWorkspace']>>;
type Strategy=Awaited<ReturnType<AriseApi['getStrategyWorkspace']>>['strategies'][number];
const EMPTY:Workspace={reviews:[],lessons:[],proposals:[]};

export function PerformanceReviewLab(){
  const [data,setData]=useState<Workspace>(EMPTY);const [analytics,setAnalytics]=useState<Analytics|null>(null);const [strategies,setStrategies]=useState<readonly Strategy[]>([]);const [evidenceIds,setEvidenceIds]=useState<readonly string[]>([]);const [showCreate,setShowCreate]=useState(false);const [error,setError]=useState<string|null>(null);
  const reload=async()=>{if(!window.arise)return;const [reviews,nextAnalytics,strategy,evidence]=await Promise.all([window.arise.getPerformanceReviewWorkspace(),window.arise.getAnalyticsWorkspace(),window.arise.getStrategyWorkspace(),window.arise.getEvidenceWorkspace()]);setData(reviews);setAnalytics(nextAnalytics);setStrategies(strategy.strategies);setEvidenceIds(evidence.events.map((event)=>event.id));};
  useEffect(()=>{void reload().catch((value:unknown)=>setError(value instanceof Error?value.message:String(value)));},[]);
  return <section className="performance-review-lab"><header><div><span>REVIEW LAB</span><strong>Dissection → Lesson → Pattern → Playbook</strong></div><button className="primary-button" onClick={()=>setShowCreate(true)}><Icon name="plus"/> Dissection</button></header>
    <div className="review-lab-columns"><section><h3>DISSECTIONS <b>{data.reviews.length}</b></h3>{data.reviews.map((review)=><ReviewCard key={review.id} review={review} onChange={setData}/>) }{!data.reviews.length?<Empty title="No Trade or Colony dissections" body="Create an evidence-backed review without rewriting the inception Thesis or Strategy versions."/>:null}</section><section><h3>LESSONS <b>{data.lessons.length}</b></h3>{data.lessons.map((lesson)=><LessonCard key={lesson.id} lesson={lesson} strategies={strategies} onChange={setData}/>) }{!data.lessons.length?<Empty title="No Lessons yet" body="A Dissection can become an Observation, then progress only through the canonical lifecycle."/>:null}</section><section><h3>PLAYBOOK UPDATES <b>{data.proposals.length}</b></h3>{data.proposals.map((proposal)=><article className="review-lab-card" key={proposal.id}><span className={`review-status ${proposal.status.toLowerCase()}`}>{proposal.status}</span><strong>{proposal.proposedChange}</strong><p>{proposal.expectedEffect}</p><small>SOURCE {proposal.sourceStrategyVersionId}</small>{proposal.status==='PROPOSED'?<button onClick={()=>window.arise?.acceptStrategyChangeProposal({proposalId:proposal.id}).then(setData).catch((value:unknown)=>setError(value instanceof Error?value.message:String(value)))}>ACCEPT AS EXPERIMENTAL VERSION</button>:<small>NEW VERSION {proposal.resultingStrategyVersionId}</small>}</article>)}{!data.proposals.length?<Empty title="No Playbook proposals" body="PLAYBOOK_RULE Lessons may propose a new immutable StrategyVersion; old versions remain historical truth."/>:null}</section></div>
    {showCreate&&analytics?<CreateReviewDialog analytics={analytics} evidenceIds={evidenceIds} onClose={()=>setShowCreate(false)} onCreated={(workspace)=>{setData(workspace);setShowCreate(false);}}/>:null}{error?<div className="error">{error}</div>:null}
  </section>;
}

function Empty({title,body}:{readonly title:string;readonly body:string}){return <div className="review-lab-empty"><Icon name="review"/><strong>{title}</strong><span>{body}</span></div>;}
interface Narrative{readonly thesis:string;readonly decision:string;readonly management:string;readonly outcome:string;readonly lesson:string}
function narrative(review:Workspace['reviews'][number]):Narrative{const current=review.currentDissection as Record<string,unknown>|null;const raw=current?.narrative as Record<string,unknown>|undefined;return {thesis:String(raw?.thesis??''),decision:String(raw?.decision??''),management:String(raw?.management??''),outcome:String(raw?.outcome??''),lesson:String(raw?.lesson??'')};}

function ReviewCard({review,onChange}:{readonly review:Workspace['reviews'][number];readonly onChange:(value:Workspace)=>void}){
  const text=narrative(review);const [expanded,setExpanded]=useState(false);const [busy,setBusy]=useState(false);
  const convert=async()=>{if(!window.arise)return;setBusy(true);try{onChange(await window.arise.createLesson({reviewId:review.id,statement:text.lesson}));}finally{setBusy(false);}};
  return <article className="review-lab-card"><span className="review-status">{review.sourceType}</span><strong>{review.title}</strong><small>IDEA {String(review.ideaVersion.id??'UNAVAILABLE')} · MAP {review.strategyMapVersion?String(review.strategyMapVersion.id):'UNAVAILABLE'}</small><button className="review-card-toggle" onClick={()=>setExpanded(!expanded)}>{expanded?'HIDE':'OPEN'} DISSECTION</button>{expanded?<div className="dissection-grid"><p><b>THESIS</b>{text.thesis}</p><p><b>DECISION</b>{text.decision}</p><p><b>MANAGEMENT</b>{text.management}</p><p><b>OUTCOME</b>{text.outcome}</p><p><b>LESSON</b>{text.lesson}</p><div className="review-evidence-chips">{review.evidence.map((item)=><span key={item.id} className={item.integrity==='VERIFIED'?'verified':'warning'}>{item.integrity}</span>)}</div></div>:null}<button disabled={busy} onClick={()=>void convert()}>CONVERT TO OBSERVATION</button></article>;
}

function LessonCard({lesson,strategies,onChange}:{readonly lesson:Workspace['lessons'][number];readonly strategies:readonly Strategy[];readonly onChange:(value:Workspace)=>void}){
  const current=lesson.currentVersion;const [showProposal,setShowProposal]=useState(false);const next=current.status==='OBSERVATION'?'REPEATED_PATTERN':current.status==='REPEATED_PATTERN'?'PLAYBOOK_RULE':current.status==='PLAYBOOK_RULE'?'MASTERED':null;
  const advance=async(status:'REPEATED_PATTERN'|'PLAYBOOK_RULE'|'MASTERED'|'ARCHIVED')=>{if(window.arise)onChange(await window.arise.advanceLesson({lessonId:lesson.id,status}));};
  return <article className="review-lab-card"><span className={`review-status ${current.status.toLowerCase()}`}>{current.status}</span><strong>{current.statement}</strong><small>VERSION {current.versionNo} · {lesson.evidence.length} EVIDENCE LINKS</small><div className="lesson-actions">{next?<button onClick={()=>void advance(next)}>ADVANCE TO {next.replaceAll('_',' ')}</button>:null}{current.status!=='ARCHIVED'?<button onClick={()=>void advance('ARCHIVED')}>ARCHIVE</button>:null}{current.status==='PLAYBOOK_RULE'&&strategies.length?<button onClick={()=>setShowProposal(true)}>PROPOSE PLAYBOOK UPDATE</button>:null}</div>{showProposal?<ProposalForm lessonId={lesson.id} strategies={strategies} onCreated={(workspace)=>{onChange(workspace);setShowProposal(false);}}/>:null}</article>;
}

function ProposalForm({lessonId,strategies,onCreated}:{readonly lessonId:string;readonly strategies:readonly Strategy[];readonly onCreated:(value:Workspace)=>void}){
  const [strategyVersionId,setStrategyVersionId]=useState(strategies[0]?.versionId??'');const [change,setChange]=useState('');const [effect,setEffect]=useState('');const [tests,setTests]=useState('');
  const submit=async()=>{if(window.arise)onCreated(await window.arise.createStrategyChangeProposal({lessonId,strategyVersionId,proposedChange:change,expectedEffect:effect,testRequirements:tests}));};
  return <div className="proposal-form"><select value={strategyVersionId} onChange={(event)=>setStrategyVersionId(event.target.value)}>{strategies.map((strategy)=><option key={strategy.versionId} value={strategy.versionId}>{strategy.name} v{strategy.versionNo}</option>)}</select><textarea aria-label="Proposed change" value={change} onChange={(event)=>setChange(event.target.value)} placeholder="Proposed playbook change"/><textarea aria-label="Expected effect" value={effect} onChange={(event)=>setEffect(event.target.value)} placeholder="Expected effect"/><textarea aria-label="Test requirements" value={tests} onChange={(event)=>setTests(event.target.value)} placeholder="Required validation"/><button disabled={!change.trim()||!effect.trim()||!tests.trim()} onClick={()=>void submit()}>CREATE PROPOSAL</button></div>;
}

function CreateReviewDialog({analytics,evidenceIds,onClose,onCreated}:{readonly analytics:Analytics;readonly evidenceIds:readonly string[];readonly onClose:()=>void;readonly onCreated:(value:Workspace)=>void}){
  const sources=useMemo(()=>[...analytics.colonies.map((colony)=>({key:`COLONY:${colony.colonyId}`,type:'COLONY' as const,id:colony.colonyId,label:`${colony.symbol} · ${colony.label}`})),...analytics.positions.map((position)=>({key:`TRADE:${position.tradeId}`,type:'TRADE' as const,id:position.tradeId,label:`Trade ${position.tradeId} · ${position.currentState}`}))],[analytics]);
  const [sourceKey,setSourceKey]=useState(sources[0]?.key??'');const [title,setTitle]=useState('');const [fields,setFields]=useState({thesis:'',decision:'',management:'',outcome:'',lesson:''});const [includeEvidence,setIncludeEvidence]=useState(true);const selected=sources.find((source)=>source.key===sourceKey);
  const set=(key:keyof typeof fields,value:string)=>setFields({...fields,[key]:value});const complete=selected&&title.trim()&&Object.values(fields).every((value)=>value.trim());
  const submit=async()=>{if(!window.arise||!selected)return;onCreated(await window.arise.createPerformanceReview({sourceType:selected.type,sourceId:selected.id,title,dissection:fields,evidenceEventIds:includeEvidence?[...evidenceIds]:[]}));};
  return <div className="modal-backdrop"><section className="modal-card review-dissection-dialog"><header><div><span>PERFORMANCE REVIEW</span><strong>Create evidence-backed Dissection</strong></div><button className="icon-button" onClick={onClose}><Icon name="close"/></button></header>{sources.length?<><label>Trade / Colony<select value={sourceKey} onChange={(event)=>setSourceKey(event.target.value)}>{sources.map((source)=><option value={source.key} key={source.key}>{source.label}</option>)}</select></label><label>Title<input value={title} onChange={(event)=>setTitle(event.target.value)} /></label><div className="dissection-form">{(['thesis','decision','management','outcome','lesson'] as const).map((key)=><label key={key}>{key.toUpperCase()}<textarea value={fields[key]} onChange={(event)=>set(key,event.target.value)}/></label>)}</div><label className="review-evidence-toggle"><input type="checkbox" checked={includeEvidence} onChange={(event)=>setIncludeEvidence(event.target.checked)}/> Link {evidenceIds.length} available Evidence Events</label><footer><button className="ghost-button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={!complete} onClick={()=>void submit()}>Create Dissection</button></footer></>:<Empty title="No reviewable Trade or Colony" body="Create a Colony before starting a performance Dissection."/>}</section></div>;
}
