import { describe,expect,it } from 'vitest';
import { createHash } from 'node:crypto';
import { MT5_PROTOCOL_VERSION, mt5SnapshotSchema, type Mt5AgentEnvelope } from '@arise/shared';
import { openDatabase } from './database';
import { Mt5Repository } from './mt5-repository';

const stamp='2026-09-11T12:00:00.000Z';
function snapshot(id:string,accountKey='broker:demo-1',complete=true){return mt5SnapshotSchema.parse({snapshotId:id,complete,capturedAt:stamp,account:complete?{accountKey,broker:'MetaQuotes',server:'Demo',login:'1001',currency:'USD',balance:10000,equity:10020,margin:20,freeMargin:10000,leverage:100,isLive:false,hedging:true,capturedAt:stamp}:null,symbols:complete?[{brokerSymbol:'EURUSD.a',canonicalSymbol:'EURUSD',digits:5,tickSize:.00001,pipSize:.0001,contractSize:100000,minVolume:.01,volumeStep:.01,maxVolume:100,stopsLevel:0,freezeLevel:0}]:[],positions:complete?[{brokerPositionKey:'ticket-7',brokerSymbol:'EURUSD.a',direction:'LONG',volume:.1,openPrice:1.1,currentPrice:1.102,stopLoss:null,takeProfit:null,openedAt:stamp,magic:0,comment:'manual'}]:[],pendingOrders:complete?[{brokerOrderKey:'order-8',brokerSymbol:'EURUSD.a',orderType:'BUY_LIMIT',direction:'LONG',volume:.1,price:1.09,stopLoss:null,takeProfit:null,placedAt:stamp,magic:0,comment:'manual'}]:[],quotes:complete?[{brokerSymbol:'EURUSD.a',bid:1.102,ask:1.1021,brokerTime:stamp,receivedAt:stamp,sequence:4}]:[],candles:complete?[{brokerSymbol:'EURUSD.a',timeframe:'M5',openTime:stamp,closeTime:null,open:1.1,high:1.103,low:1.099,close:1.102,tickVolume:22,origin:'RECOVERED'}]:[],unavailableReason:complete?null:'Terminal history unavailable'});}
function message(id:string,snap= snapshot(`snapshot-${id}`)):Mt5AgentEnvelope{return {messageId:id,correlationId:null,schemaVersion:MT5_PROTOCOL_VERSION,sentAt:stamp,payload:{kind:'BROKER_SNAPSHOT',snapshot:snap}};}

describe('M9 read-only broker reality',()=>{
  it('imports account, mapping, quote, candle, position and pending order then deduplicates message identity',()=>{const {sqlite}=openDatabase(':memory:');try{const repo=new Mt5Repository(sqlite);expect(repo.ingest(message('m1'),'STARTUP').duplicate).toBe(false);expect(repo.ingest(message('m1'),'STARTUP').duplicate).toBe(true);const view=repo.workspace();expect(view.connection.truth).toBe('VERIFIED');expect(view.connection.state).toBe('DEGRADED');expect(view.positions[0]).toMatchObject({brokerPositionKey:'ticket-7',canonicalSymbol:'EURUSD',classification:null});expect(view.pendingOrders[0]?.brokerOrderKey).toBe('order-8');expect(view.quotes[0]).toMatchObject({canonicalSymbol:'EURUSD',sequence:4});expect(view.candles[0]?.origin).toBe('RECOVERED');expect((sqlite.prepare('SELECT count(*) count FROM broker_snapshots').get() as {count:number}).count).toBe(1);}finally{sqlite.close();}});
  it('persists external classification without creating an ARISE Position',()=>{const {sqlite}=openDatabase(':memory:');try{const repo=new Mt5Repository(sqlite);repo.ingest(message('m2'));repo.classify({brokerPositionKey:'ticket-7',classification:'TRACK_AS_EXTERNAL',colonyId:null});expect(repo.workspace().positions[0]?.classification).toBe('TRACK_AS_EXTERNAL');expect((sqlite.prepare('SELECT count(*) count FROM positions').get() as {count:number}).count).toBe(0);}finally{sqlite.close();}});
  it('lets broker reality remove a vanished imported position and never recreates it',()=>{const {sqlite}=openDatabase(':memory:');try{const repo=new Mt5Repository(sqlite);repo.ingest(message('m3'));const next=snapshot('snapshot-empty');next.positions.splice(0,next.positions.length);repo.ingest(message('m4',next));expect(repo.workspace().positions).toEqual([]);expect((sqlite.prepare("SELECT count(*) count FROM broker_reality_events WHERE event_type='BROKER_CLOSED'").get() as {count:number}).count).toBe(1);}finally{sqlite.close();}});
  it('blocks on incomplete truth without converting UNKNOWN into an empty account',()=>{const {sqlite}=openDatabase(':memory:');try{const repo=new Mt5Repository(sqlite);repo.ingest(message('m5'));repo.ingest(message('m6',snapshot('snapshot-unknown','broker:demo-1',false)));const view=repo.workspace();expect(view.connection).toMatchObject({state:'BLOCKED',truth:'UNKNOWN'});expect(view.positions[0]?.realityState).toBe('UNKNOWN');expect(view.reconciliation.status).toBe('UNKNOWN');}finally{sqlite.close();}});
  it('blocks account switching and preserves the established broker account',()=>{const {sqlite}=openDatabase(':memory:');try{const repo=new Mt5Repository(sqlite);repo.ingest(message('m7'));repo.ingest(message('m8',snapshot('snapshot-other','broker:other')));const view=repo.workspace();expect(view.connection).toMatchObject({state:'BLOCKED',truth:'UNKNOWN'});expect(view.account?.accountKey).toBe('broker:demo-1');expect(view.reconciliation.discrepancies[0]?.category).toBe('UNKNOWN');}finally{sqlite.close();}});
  it('lets broker quantity win for automated exposure but does not silently mutate manual exposure',()=>{const {sqlite}=openDatabase(':memory:');try{sqlite.pragma('foreign_keys=OFF');sqlite.prepare("INSERT INTO trades VALUES ('trade-auto',NULL,'colony-1','idea-version-1',NULL,'LONG',?,'ARISE_AUTO')").run(stamp);sqlite.prepare("INSERT INTO positions VALUES ('position-auto','trade-auto','broker:demo-1','ticket-7','colony-1','colony-1','LONG',0.2,0.2,1.09,'SCOUT',?,NULL)").run(stamp);sqlite.prepare("INSERT INTO trades VALUES ('trade-manual',NULL,'colony-1','idea-version-1',NULL,'LONG',?,'ARISE_MANUAL')").run(stamp);sqlite.prepare("INSERT INTO positions VALUES ('position-manual','trade-manual','broker:demo-1','ticket-manual','colony-1','colony-1','LONG',0.3,0.3,1.08,'SCOUT',?,NULL)").run(stamp);const repo=new Mt5Repository(sqlite);repo.ingest(message('m9'));expect(sqlite.prepare("SELECT current_size size FROM positions WHERE id='position-auto'").get()).toEqual({size:0.1});expect(sqlite.prepare("SELECT current_size size FROM positions WHERE id='position-manual'").get()).toEqual({size:0.3});}finally{sqlite.close();}});
  it('audits a stale broker snapshot without rolling newer broker reality backward',()=>{const {sqlite}=openDatabase(':memory:');try{const repo=new Mt5Repository(sqlite);const newer=snapshot('snapshot-new');newer.capturedAt='2026-09-11T12:05:00.000Z';newer.account!.capturedAt=newer.capturedAt;repo.ingest(message('m10',newer));const older=snapshot('snapshot-old');older.capturedAt='2026-09-11T12:00:00.000Z';older.account!.capturedAt=older.capturedAt;older.positions.splice(0,older.positions.length);repo.ingest(message('m11',older));expect(repo.workspace().positions).toHaveLength(1);expect(sqlite.prepare("SELECT COUNT(*) count FROM broker_reality_events WHERE event_type='BROKER_CLOSED'").get()).toEqual({count:0});expect(sqlite.prepare("SELECT COUNT(*) count FROM mt5_safety_events WHERE event_type='STALE_BROKER_SNAPSHOT'").get()).toEqual({count:1});}finally{sqlite.close();}});
  it('recognizes an exact pending execution marker so restart replay can recover broker truth',()=>{const {sqlite}=openDatabase(':memory:');try{sqlite.pragma('foreign_keys=OFF');const idempotencyKey='order-plan:plan-pending:create';const payload={commandId:'command-pending',idempotencyKey,orderPlanId:'plan-pending',commandType:'CREATE_ORDER',accountKey:'broker:demo-1',brokerSymbol:'EURUSD.a',direction:'LONG',volume:.1,initialStop:1.09,brokerPositionKey:null,expectedSessionId:'old-session',createdAt:stamp,expiresAt:'2099-01-01T00:00:00.000Z',maxSpreadPips:2};sqlite.prepare('INSERT INTO order_plans VALUES (?,?,?,?,?,?,?,?)').run('plan-pending','intent-pending','deployment-pending','DEMO','broker:demo-1','old-session','{}',stamp);sqlite.prepare('INSERT INTO execution_commands VALUES (?,?,?,?,?,?,?,?,?)').run('command-pending','plan-pending',idempotencyKey,'CREATE_ORDER','UNKNOWN',1,JSON.stringify(payload),stamp,stamp);const recovered=snapshot('snapshot-recovered');recovered.positions[0]!.magic=260912;recovered.positions[0]!.comment=`ARISE:${createHash('sha256').update(idempotencyKey).digest('hex').slice(0,16)}`;const repo=new Mt5Repository(sqlite);repo.ingest(message('m12',recovered),'RECONNECT');expect(repo.workspace().reconciliation).toMatchObject({status:'MATCHED',discrepancies:[]});expect(sqlite.prepare("SELECT COUNT(*) count FROM broker_reality_events WHERE event_type='PENDING_EXECUTION_MARKER_MATCH'").get()).toEqual({count:1});}finally{sqlite.close();}});
});
