import { afterEach, describe, expect, it } from 'vitest';
import { openDatabase } from './database';
import { StrategyPackageRepository } from './strategy-package-repository';
import { StrategyRepository } from './strategy-repository';
import { withPackageChecksum, type StrategyPackageManifest } from '@arise/strategy-engine';

const opened: ReturnType<typeof openDatabase>[] = [];
afterEach(()=>{while(opened.length)opened.pop()!.sqlite.close();});
function db(){const value=openDatabase(':memory:');opened.push(value);return value;}
function manifest(version='1.0.0', dependencies: StrategyPackageManifest['dependencies']={detectors:[{id:'price_touch',versionRange:'>=1.0.0',required:true}],strategies:[],combos:[]}):StrategyPackageManifest{
  return withPackageChecksum({schemaVersion:1,packageType:'STRATEGY',packageId:'external.price-touch',name:'Price Touch Notification',description:'Observe a price touch.',version,createdAt:'2026-09-14T12:00:00.000Z',author:{name:'External',source:'Public package spec',url:null},minimumAriseVersion:'1.0.0-beta.2',capabilityRequirements:['strategy-graph','observe'],dependencies,parameters:[{key:'level',label:'Level',description:'Price',type:'PRICE',defaultValue:1.1,minimum:0,maximum:null,allowedValues:[],required:true,unit:'price',scope:'LOCAL',access:'USER_EDITABLE'}],graph:{nodes:[{id:'touch',family:'STRATEGY',label:'Price Touch',position:{x:0,y:0},timeframe:'M5',purposes:['ENTRY'],importance:'REQUIRED',executionMode:'OBSERVE',strategyRef:{packageId:'external.price-touch',versionRange:version},parameters:{level:1.1}},{id:'notify',family:'ACTION',label:'Notify',position:{x:200,y:0},timeframe:'M5',purposes:['ENTRY'],importance:'REQUIRED',executionMode:'OBSERVE',actionKey:'notify',parameters:{}}],edges:[{id:'edge',sourceNodeId:'touch',targetNodeId:'notify',sourcePort:'out',targetPort:'in'}]},timeframeMappings:[{timeframe:'M5',purposes:['ENTRY'],importance:'REQUIRED',mode:'AUTOMATED'}],evidencePolicy:{profile:'STRATEGY_EVIDENCE_ONLY',events:['CONFIRMATION'],references:['CANDLE','DECISION_TRACE','RUNTIME_NODE_EVENT']},deploymentRestrictions:{allowedModes:['OBSERVE'],preferredMode:'OBSERVE'},definition:{category:'NOTIFICATION',tags:['external'],automationCapability:'AUTOMATABLE',detector:{key:'price_touch',version:'1',evaluationMode:'ON_PRICE_UPDATE'}},template:null});
}

describe('StrategyPackageRepository',()=>{
  it('previews and atomically imports an external strategy into immutable Encyclopedia and Graph versions',()=>{const connection=db();const packages=new StrategyPackageRepository(connection.db,'1.0.0-beta.2');const source=manifest();const preview=packages.preview(JSON.stringify(source),'touch.arise-strategy');expect(preview.preview).toMatchObject({valid:true,disposition:'NEW',integrity:'VERIFIED',preferredImportMode:'OBSERVE'});const imported=packages.importValidated(source,'touch.arise-strategy',source.integrity.checksum,false,'2026-09-14T13:00:00.000Z');expect(imported).toMatchObject({status:'IMPORTED',packageId:'external.price-touch'});const strategies=new StrategyRepository(connection.db);expect(strategies.reconstructDefinition(imported.definitionId as never)?.currentVersion).toMatchObject({name:'Price Touch Notification',deploymentStatus:'EXPERIMENTAL'});expect(strategies.reconstructMap(imported.mapId as never)?.currentVersion.graph.nodes).toHaveLength(2);expect(connection.sqlite.pragma('user_version',{simple:true})).toBe(12);});
  it('is idempotent for identical content and rejects same-version modified content',()=>{const connection=db();const packages=new StrategyPackageRepository(connection.db,'1.0.0-beta.2');const first=manifest();packages.importValidated(first,'touch.arise-strategy',first.integrity.checksum,false);expect(packages.preview(JSON.stringify(first),'touch.arise-strategy').preview.disposition).toBe('IDENTICAL');expect(packages.importValidated(first,'touch.arise-strategy',first.integrity.checksum,false).status).toBe('ALREADY_IMPORTED');const changed=withPackageChecksum({...first,description:'Different',integrity:undefined} as never);const preview=packages.preview(JSON.stringify(changed),'touch.arise-strategy').preview;expect(preview).toMatchObject({valid:false,disposition:'CONFLICT'});expect(packages.listImports()).toHaveLength(1);});
  it('requires explicit upgrade confirmation and preserves prior imported versions',()=>{const connection=db();const packages=new StrategyPackageRepository(connection.db,'1.0.0-beta.2');const one=manifest();packages.importValidated(one,'touch.arise-strategy',one.integrity.checksum,false);const two=manifest('1.1.0');expect(packages.preview(JSON.stringify(two),'touch.arise-strategy').preview.disposition).toBe('UPGRADE');expect(()=>packages.importValidated(two,'touch.arise-strategy',two.integrity.checksum,false)).toThrow(/explicit/);packages.importValidated(two,'touch.arise-strategy',two.integrity.checksum,true);expect(packages.listImports()).toHaveLength(2);const aggregate=new StrategyRepository(connection.db).listDefinitions()[0]!;expect(aggregate.versions).toHaveLength(2);expect(aggregate.versions.map(v=>v.deploymentStatus)).toEqual(['EXPERIMENTAL','EXPERIMENTAL']);});
  it('reports missing, incompatible, unsupported and circular dependencies without writing',()=>{const connection=db();const packages=new StrategyPackageRepository(connection.db,'1.0.0-beta.2');const missing=manifest('1.0.0',{detectors:[{id:'price_touch',versionRange:'>=9.0.0',required:true}],strategies:[{id:'missing.strategy',versionRange:'^1.0.0',required:true}],combos:[]});const preview=packages.preview(JSON.stringify(missing),'touch.arise-strategy').preview;expect(preview.valid).toBe(false);expect(preview.dependencies.map(item=>item.status)).toContain('INCOMPATIBLE_VERSION');expect(preview.dependencies.map(item=>item.status)).toContain('MISSING');const circular=manifest('1.0.0',{detectors:[{id:'price_touch',versionRange:'1.0.0',required:true}],strategies:[{id:'external.price-touch',versionRange:'1.0.0',required:true}],combos:[]});expect(packages.preview(JSON.stringify(circular),'touch.arise-strategy').preview.errors.join(' ')).toMatch(/Circular/);expect(packages.listImports()).toHaveLength(0);});
  it('exports an imported package losslessly',()=>{const connection=db();const packages=new StrategyPackageRepository(connection.db,'1.0.0-beta.2');const source=manifest();const imported=packages.importValidated(source,'touch.arise-strategy',source.integrity.checksum,false);expect(packages.exportDefinition(imported.definitionId!)).toEqual(source);expect(packages.exportMap(imported.mapId!)).toEqual(source);});
});
